version: '3.8'

services:
    node:
        image: node:lts
        ports:
            - 9229:9229
            - 3000:3000
        volumes:
            - .:/workspace
        working_dir: /workspace
        command: yarn start
